export const vocabulary = 

[
  { "id": 1, "eng": "Hello", "tur": "Merhaba", "kaz": "Сәлем", "lat": "Sälem", "cat": "Greetings" },
  { "id": 2, "eng": "Goodbye", "tur": "Hoşça kal", "kaz": "Сау бол", "lat": "Sau bol", "cat": "Greetings" },
  { "id": 3, "eng": "Yes", "tur": "Evet", "kaz": "Иә", "lat": "İä", "cat": "Greetings" },
  { "id": 4, "eng": "No", "tur": "Hayır", "kaz": "Жоқ", "lat": "Yok", "cat": "Greetings" },
  { "id": 5, "eng": "Please", "tur": "Lütfen", "kaz": "Өтінемін", "lat": "Ötinemin", "cat": "Greetings" },
  { "id": 6, "eng": "Thank you", "tur": "Teşekkür ederim", "kaz": "Рақмет", "lat": "Rakmet", "cat": "Greetings" },
  { "id": 7, "eng": "I", "tur": "Ben", "kaz": "Мен", "lat": "Men", "cat": "Pronouns" },
  { "id": 8, "eng": "You", "tur": "Sen", "kaz": "Сен", "lat": "Sen", "cat": "Pronouns" },
  { "id": 9, "eng": "be", "tur": "ol", "kaz": "бол", "lat": "bol", "cat": "Verbs" },
  { "id": 10, "eng": "have", "tur": "sahip ol", "kaz": "ие бол", "lat": "ie bol", "cat": "Verbs" },
  { "id": 11, "eng": "do", "tur": "yap", "kaz": "жаса", "lat": "yasa", "cat": "Verbs" },
  { "id": 12, "eng": "say", "tur": "söyle", "kaz": "айт", "lat": "ayt", "cat": "Verbs" },
  { "id": 13, "eng": "go", "tur": "git", "kaz": "бар", "lat": "bar", "cat": "Verbs" },
  { "id": 14, "eng": "can", "tur": "yapabil", "kaz": "істей ал", "lat": "istei al", "cat": "Verbs" },
  { "id": 15, "eng": "get", "tur": "al", "kaz": "ал", "lat": "al", "cat": "Verbs" },
  { "id": 16, "eng": "make", "tur": "yap", "kaz": "жаса", "lat": "yasa", "cat": "Verbs" },
  { "id": 17, "eng": "know", "tur": "bil", "kaz": "біл", "lat": "bil", "cat": "Verbs" },
  { "id": 18, "eng": "think", "tur": "düşün", "kaz": "ойла", "lat": "oyla", "cat": "Verbs" },
  { "id": 19, "eng": "see", "tur": "gör", "kaz": "көр", "lat": "kör", "cat": "Verbs" },
  { "id": 20, "eng": "come", "tur": "gel", "kaz": "кел", "lat": "kel", "cat": "Verbs" },
  { "id": 21, "eng": "want", "tur": "iste", "kaz": "қала", "lat": "kala", "cat": "Verbs" },
  { "id": 22, "eng": "look", "tur": "bak", "kaz": "қара", "lat": "kara", "cat": "Verbs" },
  { "id": 23, "eng": "use", "tur": "kullan", "kaz": "қолдан", "lat": "koldan", "cat": "Verbs" },
  { "id": 24, "eng": "find", "tur": "bul", "kaz": "тап", "lat": "tap", "cat": "Verbs" },
  { "id": 25, "eng": "give", "tur": "ver", "kaz": "бер", "lat": "ber", "cat": "Verbs" },
  { "id": 26, "eng": "tell", "tur": "anlat", "kaz": "айтып бер", "lat": "aytip ber", "cat": "Verbs" },
  { "id": 27, "eng": "work", "tur": "çalış", "kaz": "жұмыс істе", "lat": "yumis iste", "cat": "Verbs" },
  { "id": 28, "eng": "call", "tur": "ara", "kaz": "қоңырау шал", "lat": "koñirau şal", "cat": "Verbs" },
  { "id": 29, "eng": "try", "tur": "dene", "kaz": "тырыс", "lat": "tiris", "cat": "Verbs" },
  { "id": 30, "eng": "ask", "tur": "sor", "kaz": "сұра", "lat": "sura", "cat": "Verbs" },
  { "id": 31, "eng": "need", "tur": "ihtiyaç duy", "kaz": "қажет ет", "lat": "kayet et", "cat": "Verbs" },
  { "id": 32, "eng": "feel", "tur": "hisset", "kaz": "сез", "lat": "sez", "cat": "Verbs" },
  { "id": 33, "eng": "become", "tur": "ol", "kaz": "бол", "lat": "bol", "cat": "Verbs" },
  { "id": 34, "eng": "leave", "tur": "ayrıl", "kaz": "кет", "lat": "ket", "cat": "Verbs" },
  { "id": 35, "eng": "put", "tur": "koy", "kaz": "қой", "lat": "koy", "cat": "Verbs" },
  { "id": 36, "eng": "mean", "tur": "anlamına gel", "kaz": "мағына білдір", "lat": "mağina bildir", "cat": "Verbs" },
  { "id": 37, "eng": "keep", "tur": "tut", "kaz": "сақта", "lat": "sakta", "cat": "Verbs" },
  { "id": 38, "eng": "let", "tur": "izin ver", "kaz": "рұқсат ет", "lat": "ruksat et", "cat": "Verbs" },
  { "id": 39, "eng": "begin", "tur": "başla", "kaz": "баста", "lat": "basta", "cat": "Verbs" },
  { "id": 40, "eng": "seem", "tur": "görün", "kaz": "көрін", "lat": "körin", "cat": "Verbs" },
  { "id": 41, "eng": "help", "tur": "yardım et", "kaz": "көмектес", "lat": "kömektes", "cat": "Verbs" },
  { "id": 42, "eng": "talk", "tur": "konuş", "kaz": "сөйле", "lat": "söyle", "cat": "Verbs" },
  { "id": 43, "eng": "turn", "tur": "dön", "kaz": "бұрыл", "lat": "buril", "cat": "Verbs" },
  { "id": 44, "eng": "start", "tur": "başla", "kaz": "баста", "lat": "basta", "cat": "Verbs" },
  { "id": 45, "eng": "show", "tur": "göster", "kaz": "көрсет", "lat": "körset", "cat": "Verbs" },
  { "id": 46, "eng": "hear", "tur": "duy", "kaz": "есті", "lat": "esti", "cat": "Verbs" },
  { "id": 47, "eng": "play", "tur": "oyna", "kaz": "ойна", "lat": "oyna", "cat": "Verbs" },
  { "id": 48, "eng": "run", "tur": "koş", "kaz": "жүгір", "lat": "yügir", "cat": "Verbs" },
  { "id": 49, "eng": "move", "tur": "hareket et", "kaz": "қозғал", "lat": "kozğal", "cat": "Verbs" },
  { "id": 50, "eng": "live", "tur": "yaşa", "kaz": "өмір сүр", "lat": "ömir sür", "cat": "Verbs" },
  { "id": 51, "eng": "believe", "tur": "inan", "kaz": "сен", "lat": "sen", "cat": "Verbs" },
  { "id": 52, "eng": "hold", "tur": "tut", "kaz": "ұста", "lat": "usta", "cat": "Verbs" },
  { "id": 53, "eng": "bring", "tur": "getir", "kaz": "әкел", "lat": "äkel", "cat": "Verbs" },
  { "id": 54, "eng": "happen", "tur": "ol", "kaz": "бол", "lat": "bol", "cat": "Verbs" },
  { "id": 55, "eng": "write", "tur": "yaz", "kaz": "жаз", "lat": "yaz", "cat": "Verbs" },
  { "id": 56, "eng": "sit", "tur": "otur", "kaz": "отыр", "lat": "otir", "cat": "Verbs" },
  { "id": 57, "eng": "stand", "tur": "ayakta dur", "kaz": "тұр", "lat": "tur", "cat": "Verbs" },
  { "id": 58, "eng": "lose", "tur": "kaybet", "kaz": "жоғалт", "lat": "yoğalt", "cat": "Verbs" },
  { "id": 59, "eng": "pay", "tur": "öde", "kaz": "төле", "lat": "töle", "cat": "Verbs" },
  { "id": 60, "eng": "meet", "tur": "tanış", "kaz": "таныс", "lat": "tanis", "cat": "Verbs" },
  { "id": 61, "eng": "include", "tur": "içer", "kaz": "қамты", "lat": "kamti", "cat": "Verbs" },
  { "id": 62, "eng": "continue", "tur": "devam et", "kaz": "жалғастыр", "lat": "yalğastir", "cat": "Verbs" },
  { "id": 63, "eng": "set", "tur": "kur", "kaz": "орнат", "lat": "ornat", "cat": "Verbs" },
  { "id": 64, "eng": "learn", "tur": "öğren", "kaz": "үйрен", "lat": "üyren", "cat": "Verbs" },
  { "id": 65, "eng": "change", "tur": "değiştir", "kaz": "өзгерт", "lat": "özgert", "cat": "Verbs" },
  { "id": 66, "eng": "lead", "tur": "yol göster", "kaz": "баста", "lat": "basta", "cat": "Verbs" },
  { "id": 67, "eng": "understand", "tur": "anla", "kaz": "түсін", "lat": "tüsin", "cat": "Verbs" },
  { "id": 68, "eng": "watch", "tur": "izle", "kaz": "қара", "lat": "kara", "cat": "Verbs" },
  { "id": 69, "eng": "follow", "tur": "takip et", "kaz": "ер", "lat": "er", "cat": "Verbs" },
  { "id": 70, "eng": "stop", "tur": "dur", "kaz": "тоқта", "lat": "tokta", "cat": "Verbs" },
  { "id": 71, "eng": "create", "tur": "yarat", "kaz": "жаса", "lat": "yasa", "cat": "Verbs" },
  { "id": 72, "eng": "speak", "tur": "konuş", "kaz": "сөйле", "lat": "söyle", "cat": "Verbs" },
  { "id": 73, "eng": "read", "tur": "oku", "kaz": "оқы", "lat": "oki", "cat": "Verbs" },
  { "id": 74, "eng": "allow", "tur": "izin ver", "kaz": "рұқсат ет", "lat": "ruksat et", "cat": "Verbs" },
  { "id": 75, "eng": "add", "tur": "ekle", "kaz": "қос", "lat": "kos", "cat": "Verbs" },
  { "id": 76, "eng": "spend", "tur": "harca", "kaz": "жұмса", "lat": "yumsa", "cat": "Verbs" },
  { "id": 77, "eng": "grow", "tur": "büyü", "kaz": "өс", "lat": "ös", "cat": "Verbs" },
  { "id": 78, "eng": "open", "tur": "aç", "kaz": "аш", "lat": "aş", "cat": "Verbs" },
  { "id": 79, "eng": "walk", "tur": "yürü", "kaz": "жүр", "lat": "yür", "cat": "Verbs" },
  { "id": 80, "eng": "win", "tur": "kazan", "kaz": "жең", "lat": "yeñ", "cat": "Verbs" },
  { "id": 81, "eng": "offer", "tur": "teklif et", "kaz": "ұсын", "lat": "usin", "cat": "Verbs" },
  { "id": 82, "eng": "remember", "tur": "hatırla", "kaz": "есіңе ал", "lat": "esiñe al", "cat": "Verbs" },
  { "id": 83, "eng": "love", "tur": "sev", "kaz": "сүй", "lat": "süy", "cat": "Verbs" },
  { "id": 84, "eng": "consider", "tur": "düşün", "kaz": "ойлан", "lat": "oylan", "cat": "Verbs" },
  { "id": 85, "eng": "appear", "tur": "görün", "kaz": "көрін", "lat": "körin", "cat": "Verbs" },
  { "id": 86, "eng": "buy", "tur": "satın al", "kaz": "сатып ал", "lat": "satip al", "cat": "Verbs" },
  { "id": 87, "eng": "wait", "tur": "bekle", "kaz": "күт", "lat": "küt", "cat": "Verbs" },
  { "id": 88, "eng": "serve", "tur": "hizmet et", "kaz": "қызмет ет", "lat": "kizmet et", "cat": "Verbs" },
  { "id": 89, "eng": "die", "tur": "öl", "kaz": "өл", "lat": "öl", "cat": "Verbs" },
  { "id": 90, "eng": "send", "tur": "gönder", "kaz": "жібер", "lat": "yiber", "cat": "Verbs" },
  { "id": 91, "eng": "expect", "tur": "bekle", "kaz": "күт", "lat": "küt", "cat": "Verbs" },
  { "id": 92, "eng": "build", "tur": "inşa et", "kaz": "сал", "lat": "sal", "cat": "Verbs" },
  { "id": 93, "eng": "stay", "tur": "kal", "kaz": "қал", "lat": "kal", "cat": "Verbs" },
  { "id": 94, "eng": "fall", "tur": "düş", "kaz": "құла", "lat": "kula", "cat": "Verbs" },
  { "id": 95, "eng": "cut", "tur": "kes", "kaz": "кес", "lat": "kes", "cat": "Verbs" },
  { "id": 96, "eng": "reach", "tur": "ulaş", "kaz": "жет", "lat": "yet", "cat": "Verbs" },
  { "id": 97, "eng": "kill", "tur": "öldür", "kaz": "өлтір", "lat": "öltir", "cat": "Verbs" },
  { "id": 98, "eng": "raise", "tur": "yükselt", "kaz": "көтер", "lat": "köter", "cat": "Verbs" },
  { "id": 99, "eng": "pass", "tur": "geç", "kaz": "өт", "lat": "öt", "cat": "Verbs" },
  { "id": 100, "eng": "sell", "tur": "sat", "kaz": "сат", "lat": "sat", "cat": "Verbs" },
  { "id": 101, "eng": "decide", "tur": "karar ver", "kaz": "шеш", "lat": "şeş", "cat": "Verbs" },
  { "id": 102, "eng": "return", "tur": "dön", "kaz": "қайт", "lat": "kayt", "cat": "Verbs" },
  { "id": 103, "eng": "explain", "tur": "açıkla", "kaz": "түсіндір", "lat": "tüsindir", "cat": "Verbs" },
  { "id": 104, "eng": "hope", "tur": "um", "kaz": "үміттен", "lat": "ümitten", "cat": "Verbs" },
  { "id": 105, "eng": "develop", "tur": "geliştir", "kaz": "дамыт", "lat": "damit", "cat": "Verbs" },
  { "id": 106, "eng": "carry", "tur": "taşı", "kaz": "апар", "lat": "apar", "cat": "Verbs" },
  { "id": 107, "eng": "break", "tur": "kır", "kaz": "сындыр", "lat": "sindir", "cat": "Verbs" },
  { "id": 108, "eng": "receive", "tur": "al", "kaz": "қабылда", "lat": "kabilda", "cat": "Verbs" },
  { "id": 109, "eng": "agree", "tur": "anlaş", "kaz": "келіс", "lat": "kelis", "cat": "Verbs" },
  { "id": 110, "eng": "eat", "tur": "ye", "kaz": "же", "lat": "ye", "cat": "Verbs" },
  { "id": 111, "eng": "drink", "tur": "iç", "kaz": "іш", "lat": "iş", "cat": "Verbs" },
  { "id": 112, "eng": "sleep", "tur": "uyu", "kaz": "ұйықта", "lat": "uyikta", "cat": "Verbs" },
  { "id": 113, "eng": "man", "tur": "adam", "kaz": "еркек", "lat": "erkek", "cat": "People" },
  { "id": 114, "eng": "woman", "tur": "kadın", "kaz": "әйел", "lat": "äyel", "cat": "People" },
  { "id": 115, "eng": "person", "tur": "kişi", "kaz": "адам", "lat": "adam", "cat": "People" },
  { "id": 116, "eng": "child", "tur": "çocuk", "kaz": "бала", "lat": "bala", "cat": "People" },
  { "id": 117, "eng": "family", "tur": "aile", "kaz": "отбасы", "lat": "otbası", "cat": "Family" },
  { "id": 118, "eng": "father", "tur": "baba", "kaz": "әке", "lat": "äke", "cat": "Family" },
  { "id": 119, "eng": "mother", "tur": "anne", "kaz": "ана", "lat": "ana", "cat": "Family" },
  { "id": 120, "eng": "brother", "tur": "erkek kardeş", "kaz": "аға/іні", "lat": "ağa/ini", "cat": "Family" },
  { "id": 121, "eng": "sister", "tur": "kız kardeş", "kaz": "әпе/қарындас", "lat": "äpe/karindas", "cat": "Family" },
  { "id": 122, "eng": "friend", "tur": "arkadaş", "kaz": "дос", "lat": "dos", "cat": "People" },
  { "id": 123, "eng": "time", "tur": "zaman", "kaz": "уақыт", "lat": "uakit", "cat": "Time" },
  { "id": 124, "eng": "year", "tur": "yıl", "kaz": "жыл", "lat": "yil", "cat": "Time" },
  { "id": 125, "eng": "day", "tur": "gün", "kaz": "күн", "lat": "kün", "cat": "Time" },
  { "id": 126, "eng": "week", "tur": "hafta", "kaz": "апта", "lat": "apta", "cat": "Time" },
  { "id": 127, "eng": "hour", "tur": "saat", "kaz": "сағат", "lat": "sağat", "cat": "Time" },
  { "id": 128, "eng": "minute", "tur": "dakika", "kaz": "минут", "lat": "minut", "cat": "Time" },
  { "id": 129, "eng": "second", "tur": "saniye", "kaz": "секунд", "lat": "sekund", "cat": "Time" },
  { "id": 130, "eng": "morning", "tur": "sabah", "kaz": "таң", "lat": "tañ", "cat": "Time" },
  { "id": 131, "eng": "night", "tur": "gece", "kaz": "түн", "lat": "tün", "cat": "Time" },
  { "id": 132, "eng": "body", "tur": "vücut", "kaz": "дене", "lat": "dene", "cat": "Body Parts" },
  { "id": 133, "eng": "head", "tur": "baş", "kaz": "бас", "lat": "bas", "cat": "Body Parts" },
  { "id": 134, "eng": "face", "tur": "yüz", "kaz": "бет", "lat": "bet", "cat": "Body Parts" },
  { "id": 135, "eng": "eye", "tur": "göz", "kaz": "көз", "lat": "köz", "cat": "Body Parts" },
  { "id": 136, "eng": "ear", "tur": "kulak", "kaz": "құлақ", "lat": "kulak", "cat": "Body Parts" },
  { "id": 137, "eng": "nose", "tur": "burun", "kaz": "мұрын", "lat": "murin", "cat": "Body Parts" },
  { "id": 138, "eng": "mouth", "tur": "ağız", "kaz": "ауыз", "lat": "auiz", "cat": "Body Parts" },
  { "id": 139, "eng": "tooth", "tur": "diş", "kaz": "тіс", "lat": "tis", "cat": "Body Parts" },
  { "id": 140, "eng": "tongue", "tur": "dil", "kaz": "тіл", "lat": "til", "cat": "Body Parts" },
  { "id": 141, "eng": "hair", "tur": "saç", "kaz": "шаш", "lat": "şaş", "cat": "Body Parts" },
  { "id": 142, "eng": "hand", "tur": "el", "kaz": "қол", "lat": "kol", "cat": "Body Parts" },
  { "id": 143, "eng": "finger", "tur": "parmak", "kaz": "саусақ", "lat": "sausak", "cat": "Body Parts" },
  { "id": 144, "eng": "arm", "tur": "kol", "kaz": "қол", "lat": "kol", "cat": "Body Parts" },
  { "id": 145, "eng": "leg", "tur": "bacak", "kaz": "аяқ", "lat": "ayak", "cat": "Body Parts" },
  { "id": 146, "eng": "foot", "tur": "ayak", "kaz": "аяқ", "lat": "ayak", "cat": "Body Parts" },
  { "id": 147, "eng": "back", "tur": "sırt", "kaz": "арқа", "lat": "arka", "cat": "Body Parts" },
  { "id": 148, "eng": "stomach", "tur": "mide", "kaz": "асқазан", "lat": "askazan", "cat": "Organs" },
  { "id": 149, "eng": "heart", "tur": "kalp", "kaz": "жүрек", "lat": "yürek", "cat": "Organs" },
  { "id": 150, "eng": "blood", "tur": "kan", "kaz": "қан", "lat": "kan", "cat": "Body Parts" },
  { "id": 151, "eng": "brain", "tur": "beyin", "kaz": "ми", "lat": "mi", "cat": "Organs" },
  { "id": 152, "eng": "bone", "tur": "kemik", "kaz": "сүйек", "lat": "süyek", "cat": "Body Parts" },
  { "id": 153, "eng": "skin", "tur": "deri", "kaz": "тері", "lat": "teri", "cat": "Body Parts" },
  { "id": 154, "eng": "neck", "tur": "boyun", "kaz": "мойын", "lat": "moyin", "cat": "Body Parts" },
  { "id": 155, "eng": "shoulder", "tur": "omuz", "kaz": "иық", "lat": "iyik", "cat": "Body Parts" },
  { "id": 156, "eng": "knee", "tur": "diz", "kaz": "тізе", "lat": "tize", "cat": "Body Parts" },
  { "id": 157, "eng": "liver", "tur": "karaciğer", "kaz": "бауыр", "lat": "bauir", "cat": "Organs" },
  { "id": 158, "eng": "lung", "tur": "akciğer", "kaz": "өкпе", "lat": "ökpe", "cat": "Organs" },
  { "id": 159, "eng": "world", "tur": "dünya", "kaz": "дүние", "lat": "dünie", "cat": "General Nouns" },
  { "id": 160, "eng": "life", "tur": "hayat", "kaz": "өмір", "lat": "ömir", "cat": "General Nouns" },
  { "id": 161, "eng": "way", "tur": "yol", "kaz": "жол", "lat": "yol", "cat": "General Nouns" },
  { "id": 162, "eng": "thing", "tur": "şey", "kaz": "зат", "lat": "zat", "cat": "General Nouns" },
  { "id": 163, "eng": "part", "tur": "parça", "kaz": "бөлік", "lat": "bölik", "cat": "General Nouns" },
  { "id": 164, "eng": "number", "tur": "sayı", "kaz": "сан", "lat": "san", "cat": "Numbers" },
  { "id": 165, "eng": "one", "tur": "bir", "kaz": "бір", "lat": "bir", "cat": "Numbers" },
  { "id": 166, "eng": "two", "tur": "iki", "kaz": "екі", "lat": "eki", "cat": "Numbers" },
  { "id": 167, "eng": "three", "tur": "üç", "kaz": "үш", "lat": "üş", "cat": "Numbers" },
  { "id": 168, "eng": "four", "tur": "dört", "kaz": "төрт", "lat": "tört", "cat": "Numbers" },
  { "id": 169, "eng": "five", "tur": "beş", "kaz": "бес", "lat": "bes", "cat": "Numbers" },
  { "id": 170, "eng": "six", "tur": "altı", "kaz": "алты", "lat": "alti", "cat": "Numbers" },
  { "id": 171, "eng": "seven", "tur": "yedi", "kaz": "жеті", "lat": "yeti", "cat": "Numbers" },
  { "id": 172, "eng": "eight", "tur": "sekiz", "kaz": "сегіз", "lat": "segiz", "cat": "Numbers" },
  { "id": 173, "eng": "nine", "tur": "dokuz", "kaz": "тоғыз", "lat": "toğiz", "cat": "Numbers" },
  { "id": 174, "eng": "ten", "tur": "on", "kaz": "он", "lat": "on", "cat": "Numbers" },
  { "id": 175, "eng": "hundred", "tur": "yüz", "kaz": "жүз", "lat": "yüz", "cat": "Numbers" },
  { "id": 176, "eng": "thousand", "tur": "bin", "kaz": "мың", "lat": "miñ", "cat": "Numbers" },
  { "id": 177, "eng": "color", "tur": "renk", "kaz": "түс", "lat": "tüs", "cat": "Colors" },
  { "id": 178, "eng": "black", "tur": "siyah", "kaz": "қара", "lat": "kara", "cat": "Colors" },
  { "id": 179, "eng": "white", "tur": "beyaz", "kaz": "ақ", "lat": "ak", "cat": "Colors" },
  { "id": 180, "eng": "red", "tur": "kırmızı", "kaz": "қызыл", "lat": "kizil", "cat": "Colors" },
  { "id": 181, "eng": "blue", "tur": "mavi", "kaz": "көк", "lat": "kök", "cat": "Colors" },
  { "id": 182, "eng": "green", "tur": "yeşil", "kaz": "жасыл", "lat": "yasil", "cat": "Colors" },
  { "id": 183, "eng": "yellow", "tur": "sarı", "kaz": "сары", "lat": "sari", "cat": "Colors" },
  { "id": 184, "eng": "brown", "tur": "kahverengi", "kaz": "қоңыр", "lat": "koñir", "cat": "Colors" },
  { "id": 185, "eng": "orange", "tur": "turuncu", "kaz": "қызғылт сары", "lat": "kizğilt sari", "cat": "Colors" },
  { "id": 186, "eng": "purple", "tur": "mor", "kaz": "күлгін", "lat": "külgin", "cat": "Colors" },
  { "id": 187, "eng": "gray", "tur": "gri", "kaz": "сұр", "lat": "sur", "cat": "Colors" },
  { "id": 188, "eng": "water", "tur": "su", "kaz": "су", "lat": "su", "cat": "Nature" },
  { "id": 189, "eng": "fire", "tur": "ateş", "kaz": "от", "lat": "ot", "cat": "Nature" },
  { "id": 190, "eng": "air", "tur": "hava", "kaz": "ауа", "lat": "aua", "cat": "Nature" },
  { "id": 191, "eng": "earth", "tur": "toprak", "kaz": "жер", "lat": "yer", "cat": "Nature" },
  { "id": 192, "eng": "sun", "tur": "güneş", "kaz": "күн", "lat": "kün", "cat": "Nature" },
  { "id": 193, "eng": "moon", "tur": "ay", "kaz": "ай", "lat": "ay", "cat": "Nature" },
  { "id": 194, "eng": "star", "tur": "yıldız", "kaz": "жұлдыз", "lat": "yuldiz", "cat": "Nature" },
  { "id": 195, "eng": "sky", "tur": "gökyüzü", "kaz": "аспан", "lat": "aspan", "cat": "Nature" },
  { "id": 196, "eng": "cloud", "tur": "bulut", "kaz": "бұлт", "lat": "bult", "cat": "Weather" },
  { "id": 197, "eng": "rain", "tur": "yağmur", "kaz": "жаңбыр", "lat": "yañbir", "cat": "Weather" },
  { "id": 198, "eng": "snow", "tur": "kar", "kaz": "қар", "lat": "kar", "cat": "Weather" },
  { "id": 199, "eng": "wind", "tur": "rüzgar", "kaz": "жел", "lat": "yel", "cat": "Weather" },
  { "id": 200, "eng": "weather", "tur": "hava durumu", "kaz": "ауа райы", "lat": "aua rayi", "cat": "Weather" },
  { "id": 201, "eng": "hot", "tur": "sıcak", "kaz": "ыстық", "lat": "istik", "cat": "Weather" },
  { "id": 202, "eng": "cold", "tur": "soğuk", "kaz": "суық", "lat": "suik", "cat": "Weather" },
  { "id": 203, "eng": "warm", "tur": "ılık", "kaz": "жылы", "lat": "yili", "cat": "Weather" },
  { "id": 204, "eng": "tree", "tur": "ağaç", "kaz": "ағаш", "lat": "ağaş", "cat": "Nature" },
  { "id": 205, "eng": "leaf", "tur": "yaprak", "kaz": "жапырақ", "lat": "yapirak", "cat": "Nature" },
  { "id": 206, "eng": "flower", "tur": "çiçek", "kaz": "гүл", "lat": "gül", "cat": "Nature" },
  { "id": 207, "eng": "grass", "tur": "çim", "kaz": "шөп", "lat": "şöp", "cat": "Nature" },
  { "id": 208, "eng": "forest", "tur": "orman", "kaz": "орман", "lat": "orman", "cat": "Nature" },
  { "id": 209, "eng": "mountain", "tur": "dağ", "kaz": "тау", "lat": "tau", "cat": "Nature" },
  { "id": 210, "eng": "river", "tur": "nehir", "kaz": "өзен", "lat": "özen", "cat": "Nature" },
  { "id": 211, "eng": "lake", "tur": "göl", "kaz": "көл", "lat": "köl", "cat": "Nature" },
  { "id": 212, "eng": "sea", "tur": "deniz", "kaz": "теңіз", "lat": "teñiz", "cat": "Nature" },
  { "id": 213, "eng": "sand", "tur": "kum", "kaz": "құм", "lat": "kum", "cat": "Nature" },
  { "id": 214, "eng": "stone", "tur": "taş", "kaz": "тас", "lat": "tas", "cat": "Nature" },
  { "id": 215, "eng": "animal", "tur": "hayvan", "kaz": "жануар", "lat": "yanuar", "cat": "Nature" },
  { "id": 216, "eng": "dog", "tur": "köpek", "kaz": "ит", "lat": "it", "cat": "Nature" },
  { "id": 217, "eng": "cat", "tur": "kedi", "kaz": "мысық", "lat": "misik", "cat": "Nature" },
  { "id": 218, "eng": "bird", "tur": "kuş", "kaz": "құс", "lat": "kus", "cat": "Nature" },
  { "id": 219, "eng": "fish", "tur": "balık", "kaz": "балық", "lat": "balik", "cat": "Nature" },
  { "id": 220, "eng": "word", "tur": "kelime", "kaz": "сөз", "lat": "söz", "cat": "Communication" },
  { "id": 221, "eng": "name", "tur": "isim", "kaz": "ат", "lat": "at", "cat": "Communication" },
  { "id": 222, "eng": "language", "tur": "dil", "kaz": "тіл", "lat": "til", "cat": "Communication" },
  { "id": 223, "eng": "question", "tur": "soru", "kaz": "сұрақ", "lat": "surak", "cat": "Communication" },
  { "id": 224, "eng": "answer", "tur": "cevap", "kaz": "жауап", "lat": "yauap", "cat": "Communication" },
  { "id": 225, "eng": "book", "tur": "kitap", "kaz": "кітап", "lat": "kitap", "cat": "Communication" },
  { "id": 226, "eng": "page", "tur": "sayfa", "kaz": "бет", "lat": "bet", "cat": "Communication" },
  { "id": 227, "eng": "letter", "tur": "mektup", "kaz": "хат", "lat": "hat", "cat": "Communication" },
  { "id": 228, "eng": "sound", "tur": "ses", "kaz": "дыбыс", "lat": "dibis", "cat": "Communication" },
  { "id": 229, "eng": "voice", "tur": "ses", "kaz": "дауыс", "lat": "dauis", "cat": "Communication" },
  { "id": 230, "eng": "good", "tur": "iyi", "kaz": "жақсы", "lat": "yaksı", "cat": "Adjectives" },
  { "id": 231, "eng": "bad", "tur": "kötü", "kaz": "жаман", "lat": "yaman", "cat": "Adjectives" },
  { "id": 232, "eng": "new", "tur": "yeni", "kaz": "жаңа", "lat": "yaña", "cat": "Adjectives" },
  { "id": 233, "eng": "old", "tur": "eski", "kaz": "ескі", "lat": "eski", "cat": "Adjectives" },
  { "id": 234, "eng": "big", "tur": "büyük", "kaz": "үлкен", "lat": "ülken", "cat": "Adjectives" },
  { "id": 235, "eng": "small", "tur": "küçük", "kaz": "кішкентай", "lat": "kişkentay", "cat": "Adjectives" },
  { "id": 236, "eng": "long", "tur": "uzun", "kaz": "ұзын", "lat": "uzin", "cat": "Adjectives" },
  { "id": 237, "eng": "short", "tur": "kısa", "kaz": "қысқа", "lat": "kiska", "cat": "Adjectives" },
  { "id": 238, "eng": "high", "tur": "yüksek", "kaz": "биік", "lat": "biik", "cat": "Adjectives" },
  { "id": 239, "eng": "low", "tur": "alçak", "kaz": "төмен", "lat": "tömen", "cat": "Adjectives" },
  { "id": 240, "eng": "right", "tur": "doğru", "kaz": "дұрыс", "lat": "duris", "cat": "Adjectives" },
  { "id": 241, "eng": "wrong", "tur": "yanlış", "kaz": "қате", "lat": "kate", "cat": "Adjectives" },
  { "id": 242, "eng": "early", "tur": "erken", "kaz": "ерте", "lat": "erte", "cat": "Adjectives" },
  { "id": 243, "eng": "late", "tur": "geç", "kaz": "кеш", "lat": "keş", "cat": "Adjectives" },
  { "id": 244, "eng": "easy", "tur": "kolay", "kaz": "оңай", "lat": "oñay", "cat": "Adjectives" },
  { "id": 245, "eng": "hard", "tur": "zor", "kaz": "қиын", "lat": "kiyin", "cat": "Adjectives" },
  { "id": 246, "eng": "beautiful", "tur": "güzel", "kaz": "әдемі", "lat": "ädemi", "cat": "Adjectives" },
  { "id": 247, "eng": "ugly", "tur": "çirkin", "kaz": "көріксіз", "lat": "köriksiz", "cat": "Adjectives" },
  { "id": 248, "eng": "and", "tur": "ve", "kaz": "және", "lat": "yäne", "cat": "Conjunctions" },
  { "id": 249, "eng": "but", "tur": "ama", "kaz": "бірақ", "lat": "birak", "cat": "Conjunctions" },
  { "id": 250, "eng": "or", "tur": "veya", "kaz": "немесе", "lat": "nemese", "cat": "Conjunctions" },
 
 
  { "id": 251, "eng": "house", "tur": "ev", "kaz": "үй", "lat": "üi", "cat": "Places" },
  { "id": 252, "eng": "school", "tur": "okul", "kaz": "мектеп", "lat": "mektep", "cat": "Places" },
  { "id": 253, "eng": "car", "tur": "araba", "kaz": "көлік", "lat": "kölik", "cat": "Transportation" },
  { "id": 254, "eng": "city", "tur": "şehir", "kaz": "қала", "lat": "kala", "cat": "Places" },
  { "id": 255, "eng": "country", "tur": "ülke", "kaz": "ел", "lat": "el", "cat": "Places" },
  { "id": 256, "eng": "road", "tur": "yol", "kaz": "жол", "lat": "yol", "cat": "Places" },
  { "id": 257, "eng": "room", "tur": "oda", "kaz": "бөлме", "lat": "bölme", "cat": "Places" },
  { "id": 258, "eng": "door", "tur": "kapı", "kaz": "есік", "lat": "esik", "cat": "Objects" },
  { "id": 259, "eng": "window", "tur": "pencere", "kaz": "терезе", "lat": "tereze", "cat": "Objects" },
  { "id": 260, "eng": "table", "tur": "masa", "kaz": "үстел", "lat": "üstel", "cat": "Objects" },
  { "id": 261, "eng": "chair", "tur": "sandalye", "kaz": "орындық", "lat": "orindik", "cat": "Objects" },
  { "id": 262, "eng": "bed", "tur": "yatak", "kaz": "төсек", "lat": "tösek", "cat": "Objects" },
  { "id": 263, "eng": "food", "tur": "yemek", "kaz": "тамақ", "lat": "tamak", "cat": "Food & Drink" },
  { "id": 264, "eng": "bread", "tur": "ekmek", "kaz": "нан", "lat": "nan", "cat": "Food & Drink" },
  { "id": 265, "eng": "meat", "tur": "et", "kaz": "ет", "lat": "et", "cat": "Food & Drink" },
  { "id": 266, "eng": "milk", "tur": "süt", "kaz": "сүт", "lat": "süt", "cat": "Food & Drink" },
  { "id": 267, "eng": "egg", "tur": "yumurta", "kaz": "жұмыртқа", "lat": "yumirtka", "cat": "Food & Drink" },
  { "id": 268, "eng": "cheese", "tur": "peynir", "kaz": "ірімшік", "lat": "irimşik", "cat": "Food & Drink" },
  { "id": 269, "eng": "fruit", "tur": "meyve", "kaz": "жеміс", "lat": "yemis", "cat": "Food & Drink" },
  { "id": 270, "eng": "vegetable", "tur": "sebze", "kaz": "көкөніс", "lat": "kökönis", "cat": "Food & Drink" },
  { "id": 271, "eng": "sugar", "tur": "şeker", "kaz": "қант", "lat": "kant", "cat": "Food & Drink" },
  { "id": 272, "eng": "salt", "tur": "tuz", "kaz": "тұз", "lat": "tuz", "cat": "Food & Drink" },
  { "id": 273, "eng": "job", "tur": "iş", "kaz": "жұмыс", "lat": "yumis", "cat": "Work" },
  { "id": 274, "eng": "money", "tur": "para", "kaz": "ақша", "lat": "akşa", "cat": "Work" },
  { "id": 275, "eng": "company", "tur": "şirket", "kaz": "компания", "lat": "kompaniia", "cat": "Work" },
  { "id": 276, "eng": "office", "tur": "ofis", "kaz": "кеңсе", "lat": "keñse", "cat": "Work" },
  { "id": 277, "eng": "lip", "tur": "dudak", "kaz": "ерін", "lat": "erin", "cat": "Body Parts" },
  { "id": 278, "eng": "chin", "tur": "çene", "kaz": "иек", "lat": "iek", "cat": "Body Parts" },
  { "id": 279, "eng": "chest", "tur": "göğüs", "kaz": "кеуде", "lat": "keude", "cat": "Body Parts" },
  { "id": 280, "eng": "waist", "tur": "bel", "kaz": "бел", "lat": "bel", "cat": "Body Parts" },
  { "id": 281, "eng": "hip", "tur": "kalça", "kaz": "жамбас", "lat": "yambas", "cat": "Body Parts" },
  { "id": 282, "eng": "thumb", "tur": "baş parmak", "kaz": "бас бармақ", "lat": "bas barmak", "cat": "Body Parts" },
  { "id": 283, "eng": "nail", "tur": "tırnak", "kaz": "тырнақ", "lat": "tirnak", "cat": "Body Parts" },
  { "id": 284, "eng": "eyebrow", "tur": "kaş", "kaz": "қас", "lat": "kas", "cat": "Body Parts" },
  { "id": 285, "eng": "eyelash", "tur": "kirpik", "kaz": "кірпік", "lat": "kirpik", "cat": "Body Parts" },
  { "id": 286, "eng": "forehead", "tur": "alın", "kaz": "маңдай", "lat": "mañday", "cat": "Body Parts" },
  { "id": 287, "eng": "cheek", "tur": "yanak", "kaz": "бет", "lat": "bet", "cat": "Body Parts" },
  { "id": 288, "eng": "muscle", "tur": "kas", "kaz": "бұлшықет", "lat": "bulşik_et", "cat": "Body Parts" },
  { "id": 289, "eng": "throat", "tur": "boğaz", "kaz": "тамақ", "lat": "tamak", "cat": "Body Parts" },
  { "id": 290, "eng": "kidney", "tur": "böbrek", "kaz": "бүйрек", "lat": "büyrek", "cat": "Organs" },
  { "id": 291, "eng": "intestine", "tur": "bağırsak", "kaz": "ішек", "lat": "işek", "cat": "Organs" },
  { "id": 292, "eng": "vein", "tur": "damar", "kaz": "тамыр", "lat": "tamir", "cat": "Body Parts" },
  { "id": 293, "eng": "island", "tur": "ada", "kaz": "арал", "lat": "aral", "cat": "Nature" },
  { "id": 294, "eng": "coast", "tur": "kıyı", "kaz": "жағалау", "lat": "yağalau", "cat": "Nature" },
  { "id": 295, "eng": "beach", "tur": "plaj", "kaz": "жағажай", "lat": "yağayay", "cat": "Nature" },
  { "id": 296, "eng": "desert", "tur": "çöl", "kaz": "шөл", "lat": "şöl", "cat": "Nature" },
  { "id": 297, "eng": "valley", "tur": "vadi", "kaz": "алқап", "lat": "alkap", "cat": "Nature" },
  { "id": 298, "eng": "hill", "tur": "tepe", "kaz": "төбе", "lat": "töbe", "cat": "Nature" },
  { "id": 299, "eng": "field", "tur": "tarla", "kaz": "егістік", "lat": "egistik", "cat": "Nature" },
  { "id": 300, "eng": "root", "tur": "kök", "kaz": "тамыр", "lat": "tamir", "cat": "Nature" },
  { "id": 301, "eng": "branch", "tur": "dal", "kaz": "бұтақ", "lat": "butak", "cat": "Nature" },
  { "id": 302, "eng": "plant", "tur": "bitki", "kaz": "өсімдік", "lat": "ösimdik", "cat": "Nature" },
  { "id": 303, "eng": "ice", "tur": "buz", "kaz": "мұз", "lat": "muz", "cat": "Weather" },
  { "id": 304, "eng": "storm", "tur": "fırtına", "kaz": "дауыл", "lat": "dauil", "cat": "Weather" },
  { "id": 305, "eng": "fog", "tur": "sis", "kaz": "тұман", "lat": "tuman", "cat": "Weather" },
  { "id": 306, "eng": "lightning", "tur": "şimşek", "kaz": "найзағай", "lat": "nayzağay", "cat": "Weather" },
  { "id": 307, "eng": "thunder", "tur": "gök gürültüsü", "kaz": "күн күркіреуі", "lat": "kün kürkireui", "cat": "Weather" },
  { "id": 308, "eng": "temperature", "tur": "sıcaklık", "kaz": "температура", "lat": "temperatura", "cat": "Weather" },
  { "id": 309, "eng": "story", "tur": "hikaye", "kaz": "әңгіме", "lat": "äñgime", "cat": "Communication" },
  { "id": 310, "eng": "message", "tur": "mesaj", "kaz": "хабарлама", "lat": "habarlama", "cat": "Communication" },
  { "id": 311, "eng": "information", "tur": "bilgi", "kaz": "ақпарат", "lat": "akparat", "cat": "Communication" },
  { "id": 312, "eng": "news", "tur": "haber", "kaz": "жаңалық", "lat": "yañalik", "cat": "Communication" },
  { "id": 313, "eng": "paper", "tur": "kağıt", "kaz": "қағаз", "lat": "kağaz", "cat": "Objects" },
  { "id": 314, "eng": "pen", "tur": "kalem", "kaz": "қалам", "lat": "kalam", "cat": "Objects" },
  { "id": 315, "eng": "pencil", "tur": "kurşun kalem", "kaz": "қарындаш", "lat": "karindaş", "cat": "Objects" },
  { "id": 316, "eng": "call", "tur": "arama", "kaz": "қоңырау", "lat": "koñirau", "cat": "Communication" },
  { "id": 317, "eng": "conversation", "tur": "sohbet", "kaz": "әңгімелесу", "lat": "äñgimelesu", "cat": "Communication" },
  { "id": 318, "eng": "idea", "tur": "fikir", "kaz": "идея", "lat": "ideia", "cat": "Abstract" },
  { "id": 319, "eng": "problem", "tur": "sorun", "kaz": "мәселе", "lat": "mäsele", "cat": "Abstract" },
  { "id": 320, "eng": "reason", "tur": "sebep", "kaz": "себеп", "lat": "sebep", "cat": "Abstract" },
  { "id": 321, "eng": "result", "tur": "sonuç", "kaz": "нәтиже", "lat": "nätie", "cat": "Abstract" },
  { "id": 322, "eng": "art", "tur": "sanat", "kaz": "өнер", "lat": "öner", "cat": "Culture" },
  { "id": 323, "eng": "music", "tur": "müzik", "kaz": "музыка", "lat": "muzika", "cat": "Culture" },
  { "id": 324, "eng": "song", "tur": "şarkı", "kaz": "ән", "lat": "än", "cat": "Culture" },
  { "id": 325, "eng": "war", "tur": "savaş", "kaz": "соғыс", "lat": "soğis", "cat": "Society" },
  { "id": 326, "eng": "peace", "tur": "barış", "kaz": "бейбітшілік", "lat": "beybitşilik", "cat": "Society" },
  { "id": 327, "eng": "law", "tur": "hukuk", "kaz": "заң", "lat": "zañ", "cat": "Society" },
  { "id": 328, "eng": "government", "tur": "hükümet", "kaz": "үкімет", "lat": "ükimet", "cat": "Society" },
  { "id": 329, "eng": "president", "tur": "başkan", "kaz": "президент", "lat": "prezident", "cat": "Society" },
  { "id": 330, "eng": "history", "tur": "tarih", "kaz": "тарих", "lat": "tarih", "cat": "Education" },
  { "id": 331, "eng": "science", "tur": "bilim", "kaz": "ғылым", "lat": "ğilim", "cat": "Education" },
  { "id": 332, "eng": "math", "tur": "matematik", "kaz": "математика", "lat": "matematika", "cat": "Education" },
  { "id": 333, "eng": "student", "tur": "öğrenci", "kaz": "оқушы", "lat": "okuşi", "cat": "Education" },
  { "id": 334, "eng": "teacher", "tur": "öğretmen", "kaz": "мұғалім", "lat": "muğalim", "cat": "Education" },
  { "id": 335, "eng": "class", "tur": "sınıf", "kaz": "сынып", "lat": "sinip", "cat": "Education" },
  { "id": 336, "eng": "true", "tur": "doğru", "kaz": "шын", "lat": "şin", "cat": "Adjectives" },
  { "id": 337, "eng": "false", "tur": "yanlış", "kaz": "жалған", "lat": "yalğan", "cat": "Adjectives" },
  { "id": 338, "eng": "happy", "tur": "mutlu", "kaz": "бақытты", "lat": "bakitti", "cat": "Adjectives" },
  { "id": 339, "eng": "sad", "tur": "üzgün", "kaz": "мұңды", "lat": "muñdi", "cat": "Adjectives" },
  { "id": 340, "eng": "strong", "tur": "güçlü", "kaz": "күшті", "lat": "küşti", "cat": "Adjectives" },
  { "id": 341, "eng": "weak", "tur": "zayıf", "kaz": "әлсіз", "lat": "älsiz", "cat": "Adjectives" },
  { "id": 342, "eng": "rich", "tur": "zengin", "kaz": "бай", "lat": "bay", "cat": "Adjectives" },
  { "id": 343, "eng": "poor", "tur": "fakir", "kaz": "кедей", "lat": "kedey", "cat": "Adjectives" },
  { "id": 344, "eng": "clean", "tur": "temiz", "kaz": "таза", "lat": "taza", "cat": "Adjectives" },
  { "id": 345, "eng": "dirty", "tur": "kirli", "kaz": "лас", "lat": "las", "cat": "Adjectives" },
  { "id": 346, "eng": "full", "tur": "dolu", "kaz": "толы", "lat": "toli", "cat": "Adjectives" },
  { "id": 347, "eng": "empty", "tur": "boş", "kaz": "бос", "lat": "bos", "cat": "Adjectives" },
  { "id": 348, "eng": "light", "tur": "hafif", "kaz": "жеңіл", "lat": "yeñil", "cat": "Adjectives" },
  { "id": 349, "eng": "heavy", "tur": "ağır", "kaz": "ауыр", "lat": "auir", "cat": "Adjectives" },
  { "id": 350, "eng": "dark", "tur": "karanlık", "kaz": "қараңғы", "lat": "karañği", "cat": "Adjectives" },
  { "id": 351, "eng": "bright", "tur": "parlak", "kaz": "жарық", "lat": "yarik", "cat": "Adjectives" },
  { "id": 352, "eng": "open", "tur": "açık", "kaz": "ашық", "lat": "aşik", "cat": "Adjectives" },
  { "id": 353, "eng": "closed", "tur": "kapalı", "kaz": "жабық", "lat": "yabik", "cat": "Adjectives" },
  { "id": 354, "eng": "fast", "tur": "hızlı", "kaz": "жылдам", "lat": "yildam", "cat": "Adjectives" },
  { "id": 355, "eng": "slow", "tur": "yavaş", "kaz": "баяу", "lat": "baiau", "cat": "Adjectives" },
  { "id": 356, "eng": "quiet", "tur": "sessiz", "kaz": "тыныш", "lat": "tiniş", "cat": "Adjectives" },
  { "id": 357, "eng": "loud", "tur": "yüksek sesli", "kaz": "қатты", "lat": "katti", "cat": "Adjectives" },
  { "id": 358, "eng": "soft", "tur": "yumuşak", "kaz": "жұмсақ", "lat": "yumsaқ", "cat": "Adjectives" },
  { "id": 359, "eng": "young", "tur": "genç", "kaz": "жас", "lat": "yas", "cat": "Adjectives" },
  { "id": 360, "eng": "able", "tur": "muktedir", "kaz": "қабілетті", "lat": "kabiletti", "cat": "Adjectives" },
  { "id": 361, "eng": "different", "tur": "farklı", "kaz": "басқа", "lat": "baska", "cat": "Adjectives" },
  { "id": 362, "eng": "same", "tur": "aynı", "kaz": "бірдей", "lat": "birdey", "cat": "Adjectives" },
  { "id": 363, "eng": "important", "tur": "önemli", "kaz": "маңызды", "lat": "mañizdi", "cat": "Adjectives" },
  { "id": 364, "eng": "public", "tur": "halka açık", "kaz": "қоғамдық", "lat": "koğamdik", "cat": "Adjectives" },
  { "id": 365, "eng": "private", "tur": "özel", "kaz": "жеке", "lat": "yeke", "cat": "Adjectives" },
  { "id": 366, "eng": "possible", "tur": "mümkün", "kaz": "мүмкін", "lat": "mümkin", "cat": "Adjectives" },
  { "id": 367, "eng": "impossible", "tur": "imkansız", "kaz": "мүмкін емес", "lat": "mümkin emes", "cat": "Adjectives" },
  { "id": 368, "eng": "sure", "tur": "emin", "kaz": "сенімді", "lat": "senimdi", "cat": "Adjectives" },
  { "id": 369, "eng": "he", "tur": "o", "kaz": "ол", "lat": "ol", "cat": "Pronouns" },
  { "id": 370, "eng": "she", "tur": "o", "kaz": "ол", "lat": "ol", "cat": "Pronouns" },
  { "id": 371, "eng": "it", "tur": "o", "kaz": "ол", "lat": "ol", "cat": "Pronouns" },
  { "id": 372, "eng": "we", "tur": "biz", "kaz": "біз", "lat": "biz", "cat": "Pronouns" },
  { "id": 373, "eng": "they", "tur": "onlar", "kaz": "олар", "lat": "olar", "cat": "Pronouns" },
  { "id": 374, "eng": "what", "tur": "ne", "kaz": "не", "lat": "ne", "cat": "Questions" },
  { "id": 375, "eng": "who", "tur": "kim", "kaz": "кім", "lat": "kim", "cat": "Questions" },
  { "id": 376, "eng": "where", "tur": "nerede", "kaz": "қайда", "lat": "kayda", "cat": "Questions" },
  { "id": 377, "eng": "when", "tur": "ne zaman", "kaz": "қашан", "lat": "kaşan", "cat": "Questions" },
  { "id": 378, "eng": "why", "tur": "neden", "kaz": "неге", "lat": "nege", "cat": "Questions" },
  { "id": 379, "eng": "how", "tur": "nasıl", "kaz": "қалай", "lat": "kalay", "cat": "Questions" },
  { "id": 380, "eng": "which", "tur": "hangi", "kaz": "қайсы", "lat": "kaysi", "cat": "Questions" },
  { "id": 381, "eng": "always", "tur": "her zaman", "kaz": "әрдайым", "lat": "ärdayim", "cat": "Adverbs" },
  { "id": 382, "eng": "never", "tur": "asla", "kaz": "ешқашан", "lat": "eşkaşan", "cat": "Adverbs" },
  { "id": 383, "eng": "sometimes", "tur": "bazen", "kaz": "кейде", "lat": "keyde", "cat": "Adverbs" },
  { "id": 384, "eng": "often", "tur": "sık sık", "kaz": "жиі", "lat": "yii", "cat": "Adverbs" },
  { "id": 385, "eng": "usually", "tur": "genellikle", "kaz": "әдетте", "lat": "ädette", "cat": "Adverbs" },
  { "id": 386, "eng": "here", "tur": "burada", "kaz": "мұнда", "lat": "munda", "cat": "Adverbs" },
  { "id": 387, "eng": "there", "tur": "orada", "kaz": "анда", "lat": "anda", "cat": "Adverbs" },
  { "id": 388, "eng": "now", "tur": "şimdi", "kaz": "қазір", "lat": "käzir", "cat": "Adverbs" },
  { "id": 389, "eng": "then", "tur": "sonra", "kaz": "содан кейін", "lat": "sodan keyin", "cat": "Adverbs" },
  { "id": 390, "eng": "today", "tur": "bugün", "kaz": "бүгін", "lat": "bügin", "cat": "Time" },
  { "id": 391, "eng": "yesterday", "tur": "dün", "kaz": "кеше", "lat": "keşe", "cat": "Time" },
  { "id": 392, "eng": "tomorrow", "tur": "yarın", "kaz": "ертең", "lat": "erteñ", "cat": "Time" },
  { "id": 393, "eng": "tonight", "tur": "bu gece", "kaz": "бүгін түнде", "lat": "bügin tünde", "cat": "Time" },
  { "id": 394, "eng": "because", "tur": "çünkü", "kaz": "себебі", "lat": "sebebi", "cat": "Conjunctions" },
  { "id": 395, "eng": "if", "tur": "eğer", "kaz": "егер", "lat": "eger", "cat": "Conjunctions" },
  { "id": 396, "eng": "so", "tur": "bu yüzden", "kaz": "сондықтан", "lat": "sondiktan", "cat": "Conjunctions" },
  { "id": 397, "eng": "fly", "tur": "uç", "kaz": "ұш", "lat": "uş", "cat": "Verbs" },
  { "id": 398, "eng": "swim", "tur": "yüz", "kaz": "жүз", "lat": "yüz", "cat": "Verbs" },
  { "id": 399, "eng": "cook", "tur": "pişir", "kaz": "пісір", "lat": "pisir", "cat": "Verbs" },
  { "id": 400, "eng": "wash", "tur": "yıka", "kaz": "жу", "lat": "yu", "cat": "Verbs" },
  { "id": 401, "eng": "clean", "tur": "temizle", "kaz": "тазала", "lat": "tazala", "cat": "Verbs" },
  { "id": 402, "eng": "dance", "tur": "dans et", "kaz": "биле", "lat": "bile", "cat": "Verbs" },
  { "id": 403, "eng": "sing", "tur": "şarkı söyle", "kaz": "ән айт", "lat": "än ayt", "cat": "Verbs" },
  { "id": 404, "eng": "laugh", "tur": "gül", "kaz": "күл", "lat": "kül", "cat": "Verbs" },
  { "id": 405, "eng": "cry", "tur": "ağla", "kaz": "жыла", "lat": "yila", "cat": "Verbs" },
  { "id": 406, "eng": "smile", "tur": "gülümse", "kaz": "күлімде", "lat": "külimde", "cat": "Verbs" },
  { "id": 407, "eng": "fight", "tur": "dövüş", "kaz": "төбелес", "lat": "töbeles", "cat": "Verbs" },
  { "id": 408, "eng": "push", "tur": "it", "kaz": "итер", "lat": "iter", "cat": "Verbs" },
  { "id": 409, "eng": "pull", "tur": "çek", "kaz": "тарт", "lat": "tart", "cat": "Verbs" },
  { "id": 410, "eng": "throw", "tur": "at", "kaz": "лақтыр", "lat": "laktir", "cat": "Verbs" },
  { "id": 411, "eng": "catch", "tur": "yakala", "kaz": "ұстап ал", "lat": "ustap al", "cat": "Verbs" },
  { "id": 412, "eng": "climb", "tur": "tırman", "kaz": "өрмеле", "lat": "örmele", "cat": "Verbs" },
  { "id": 413, "eng": "drive", "tur": "sür", "kaz": "айда", "lat": "ayda", "cat": "Verbs" },
  { "id": 414, "eng": "ride", "tur": "bin", "kaz": "мін", "lat": "min", "cat": "Verbs" },
  { "id": 415, "eng": "wear", "tur": "giy", "kaz": "ки", "lat": "ki", "cat": "Verbs" },
  { "id": 416, "eng": "clothing", "tur": "giyim", "kaz": "киім", "lat": "kiim", "cat": "Clothing" },
  { "id": 417, "eng": "shirt", "tur": "gömlek", "kaz": "жейде", "lat": "yeyde", "cat": "Clothing" },
  { "id": 418, "eng": "pants", "tur": "pantolon", "kaz": "шалбар", "lat": "şalbar", "cat": "Clothing" },
  { "id": 419, "eng": "shoes", "tur": "ayakkabı", "kaz": "аяқ киім", "lat": "ayak kiim", "cat": "Clothing" },
  { "id": 420, "eng": "hat", "tur": "şapka", "kaz": "қалпақ", "lat": "kalpak", "cat": "Clothing" },
  { "id": 421, "eng": "coat", "tur": "palto", "kaz": "пальто", "lat": "pal'to", "cat": "Clothing" },
  { "id": 422, "eng": "dress", "tur": "elbise", "kaz": "көйлек", "lat": "köylek", "cat": "Clothing" },
  { "id": 423, "eng": "socks", "tur": "çorap", "kaz": "шұлық", "lat": "şulik", "cat": "Clothing" },
  { "id": 424, "eng": "north", "tur": "kuzey", "kaz": "солтүстік", "lat": "soltüstik", "cat": "Directions" },
  { "id": 425, "eng": "south", "tur": "güney", "kaz": "оңтүстік", "lat": "oñtüstik", "cat": "Directions" },
  { "id": 426, "eng": "east", "tur": "doğu", "kaz": "шығыс", "lat": "şigis", "cat": "Directions" },
  { "id": 427, "eng": "west", "tur": "batı", "kaz": "батыс", "lat": "batis", "cat": "Directions" },
  { "id": 428, "eng": "left", "tur": "sol", "kaz": "сол", "lat": "sol", "cat": "Directions" },
  { "id": 429, "eng": "right", "tur": "sağ", "kaz": "оң", "lat": "oñ", "cat": "Directions" },
  { "id": 430, "eng": "up", "tur": "yukarı", "kaz": "жоғары", "lat": "yoğari", "cat": "Directions" },
  { "id": 431, "eng": "down", "tur": "aşağı", "kaz": "төмен", "lat": "tömen", "cat": "Directions" },
  { "id": 432, "eng": "inside", "tur": "içeri", "kaz": "ішінде", "lat": "işinde", "cat": "Directions" },
  { "id": 433, "eng": "outside", "tur": "dışarı", "kaz": "сыртында", "lat": "sirtinda", "cat": "Directions" },
  { "id": 434, "eng": "spring", "tur": "ilkbahar", "kaz": "көктем", "lat": "köktem", "cat": "Seasons" },
  { "id": 435, "eng": "summer", "tur": "yaz", "kaz": "жаз", "lat": "yaz", "cat": "Seasons" },
  { "id": 436, "eng": "autumn", "tur": "sonbahar", "kaz": "күз", "lat": "küz", "cat": "Seasons" },
  { "id": 437, "eng": "winter", "tur": "kış", "kaz": "қыс", "lat": "kis", "cat": "Seasons" },
  { "id": 438, "eng": "boy", "tur": "oğlan", "kaz": "ұл", "lat": "ul", "cat": "People" },
  { "id": 439, "eng": "girl", "tur": "kız", "kaz": "қыз", "lat": "kiz", "cat": "People" },
  { "id": 440, "eng": "baby", "tur": "bebek", "kaz": "сәби", "lat": "säbi", "cat": "People" },
  { "id": 441, "eng": "husband", "tur": "koca", "kaz": "күйеу", "lat": "küyeu", "cat": "Family" },
  { "id": 442, "eng": "wife", "tur": "karı", "kaz": "әйел", "lat": "äyel", "cat": "Family" },
  { "id": 443, "eng": "parent", "tur": "ebeveyn", "kaz": "ата-ана", "lat": "ata-ana", "cat": "Family" },
  { "id": 444, "eng": "son", "tur": "oğul", "kaz": "ұл", "lat": "ul", "cat": "Family" },
  { "id": 445, "eng": "daughter", "tur": "kız evlat", "kaz": "қыз", "lat": "kiz", "cat": "Family" },
  { "id": 446, "eng": "love", "tur": "aşk", "kaz": "махаббат", "lat": "mahabbat", "cat": "Emotions" },
  { "id": 447, "eng": "hate", "tur": "nefret", "kaz": "жек көру", "lat": "yek köru", "cat": "Emotions" },
  { "id": 448, "eng": "fear", "tur": "korku", "kaz": "қорқыныш", "lat": "korkiniş", "cat": "Emotions" },
  { "id": 449, "eng": "anger", "tur": "öfke", "kaz": "ашу", "lat": "aşu", "cat": "Emotions" },
  { "id": 450, "eng": "joy", "tur": "neşe", "kaz": "қуаныш", "lat": "kuaniş", "cat": "Emotions" },
  { "id": 451, "eng": "pain", "tur": "acı", "kaz": "ауырсыну", "lat": "auirsinu", "cat": "Emotions" },
  { "id": 452, "eng": "pleasure", "tur": "zevk", "kaz": "ләззат", "lat": "läzzat", "cat": "Emotions" },
  { "id": 453, "eng": "dream", "tur": "rüya", "kaz": "түс", "lat": "tüs", "cat": "Abstract" },
  { "id": 454, "eng": "hope", "tur": "umut", "kaz": "үміт", "lat": "ümit", "cat": "Abstract" },
  { "id": 455, "eng": "light", "tur": "ışık", "kaz": "жарық", "lat": "yarik", "cat": "Nature" },
  { "id": 456, "eng": "darkness", "tur": "karanlık", "kaz": "қараңғылық", "lat": "karañğilik", "cat": "Nature" },
  { "id": 457, "eng": "life", "tur": "yaşam", "kaz": "тіршілік", "lat": "tirşilik", "cat": "Abstract" },
  { "id": 458, "eng": "death", "tur": "ölüm", "kaz": "өлім", "lat": "ölim", "cat": "Abstract" },
  { "id": 459, "eng": "health", "tur": "sağlık", "kaz": "денсаулық", "lat": "densaulik", "cat": "Health" },
  { "id": 460, "eng": "sickness", "tur": "hastalık", "kaz": "ауру", "lat": "auru", "cat": "Health" },
  { "id": 461, "eng": "doctor", "tur": "doktor", "kaz": "дәрігер", "lat": "däriger", "cat": "Health" },
  { "id": 462, "eng": "hospital", "tur": "hastane", "kaz": "аурухана", "lat": "auruhana", "cat": "Health" },
  { "id": 463, "eng": "medicine", "tur": "ilaç", "kaz": "дәрі", "lat": "däri", "cat": "Health" },
  { "id": 464, "eng": "sleep", "tur": "uyku", "kaz": "ұйқы", "lat": "uyki", "cat": "Health" },
  { "id": 465, "eng": "wake", "tur": "uyan", "kaz": "оян", "lat": "oyan", "cat": "Verbs" },
  { "id": 466, "eng": "marry", "tur": "evlen", "kaz": "үйлен", "lat": "üylen", "cat": "Verbs" },
  { "id": 467, "eng": "divorce", "tur": "boşan", "kaz": "ажырас", "lat": "ayiras", "cat": "Verbs" },
  { "id": 468, "eng": "teach", "tur": "öğret", "kaz": "оқыт", "lat": "okit", "cat": "Verbs" },
  { "id": 469, "eng": "study", "tur": "ders çalış", "kaz": "оқы", "lat": "oki", "cat": "Verbs" },
  { "id": 470, "eng": "travel", "tur": "seyahat et", "kaz": "саяхатта", "lat": "saiahatta", "cat": "Verbs" },
  { "id": 471, "eng": "rest", "tur": "dinlen", "kaz": "демал", "lat": "demal", "cat": "Verbs" },
  { "id": 472, "eng": "forget", "tur": "unut", "kaz": "ұмыт", "lat": "umit", "cat": "Verbs" },
  { "id": 473, "eng": "forgive", "tur": "affet", "kaz": "кешір", "lat": "keşir", "cat": "Verbs" },
  { "id": 474, "eng": "choose", "tur": "seç", "kaz": "таңда", "lat": "tañda", "cat": "Verbs" },
  { "id": 475, "eng": "finish", "tur": "bitir", "kaz": "аяқта", "lat": "aiakta", "cat": "Verbs" },
  { "id": 476, "eng": "control", "tur": "kontrol et", "kaz": "бақыла", "lat": "bakila", "cat": "Verbs" },
  { "id": 477, "eng": "attack", "tur": "saldır", "kaz": "шабуылда", "lat": "şabuilda", "cat": "Verbs" },
  { "id": 478, "eng": "protect", "tur": "koru", "kaz": "қорға", "lat": "korğa", "cat": "Verbs" },
  { "id": 479, "eng": "support", "tur": "destekle", "kaz": "қолда", "lat": "kolda", "cat": "Verbs" },
  { "id": 480, "eng": "smoke", "tur": "sigara iç", "kaz": "темекі шек", "lat": "temeki şek", "cat": "Verbs" },
  { "id": 481, "eng": "touch", "tur": "dokun", "kaz": "ти", "lat": "ti", "cat": "Verbs" },
  { "id": 482, "eng": "smell", "tur": "kokla", "kaz": "иіске", "lat": "iiske", "cat": "Verbs" },
  { "id": 483, "eng": "taste", "tur": "tat", "kaz": "дәмін тат", "lat": "dämin tat", "cat": "Verbs" },
  { "id": 484, "eng": "listen", "tur": "dinle", "kaz": "тыңда", "lat": "tiñda", "cat": "Verbs" },
  { "id": 485, "eng": "breathe", "tur": "nefes al", "kaz": "демал", "lat": "demal", "cat": "Verbs" },
  { "id": 486, "eng": "point", "tur": "işaret et", "kaz": "нұсқа", "lat": "nuska", "cat": "Verbs" },
  { "id": 487, "eng": "shout", "tur": "bağır", "kaz": "айқайла", "lat": "aykayla", "cat": "Verbs" },
  { "id": 488, "eng": "whisper", "tur": "fısılda", "kaz": "сыбырла", "lat": "sibirla", "cat": "Verbs" },
  { "id": 489, "eng": "count", "tur": "say", "kaz": "сана", "lat": "sana", "cat": "Verbs" },
  { "id": 490, "eng": "measure", "tur": "ölç", "kaz": "өлше", "lat": "ölşe", "cat": "Verbs" },
  { "id": 491, "eng": "weigh", "tur": "tart", "kaz": "өлше", "lat": "ölşe", "cat": "Verbs" },
  { "id": 492, "eng": "prepare", "tur": "hazırla", "kaz": "дайында", "lat": "dayinda", "cat": "Verbs" },
  { "id": 493, "eng": "search", "tur": "ara", "kaz": "ізде", "lat": "izde", "cat": "Verbs" },
  { "id": 494, "eng": "discover", "tur": "keşfet", "kaz": "аш", "lat": "aş", "cat": "Verbs" },
  { "id": 495, "eng": "hide", "tur": "saklan", "kaz": "жасырын", "lat": "yasirin", "cat": "Verbs" },
  { "id": 496, "eng": "cost", "tur": "mal ol", "kaz": "тұр", "lat": "tur", "cat": "Verbs" },
  { "id": 497, "eng": "price", "tur": "fiyat", "kaz": "баға", "lat": "bağa", "cat": "Work" },
  { "id": 498, "eng": "tax", "tur": "vergi", "kaz": "салық", "lat": "salik", "cat": "Work" },
  { "id": 499, "eng": "tool", "tur": "alet", "kaz": "құрал", "lat": "kural", "cat": "Objects" },
  { "id": 500, "eng": "metal", "tur": "metal", "kaz": "металл", "lat": "metall", "cat": "Objects" }
];
